### ISSUE TITLE
Es posible agregar los signos de <>?

### ISSUE THREAD

**Issue by EmirSc** [logico-dev/Spanish-Dvorak-Layout#2]
titulo

**Comment by janoamaral** [comment]
Necesitaría más información sobre tu teclado. Los que probamos tienen la tecla **VK_OEM_102** que corresponde a los signos < y >. ¿Si ejecutas el Keyboard Layout Creator (KLC) se ve el layout con la tecla correspondiente? (si posas el mouse sobre la tecla se ve el valor de la tecla virtual). Por otro lado a veces es necesario cerrar sesión de Windows y volverla a iniciar para que tome el layout correctamente.

![DvorakSP](https://user-images.githubusercontent.com/10008708/73689143-5570da80-46ac-11ea-9fcf-d3069951b8f7.jpg)

**Comment by EmirSc** [comment]
al cargar el teclado en KLC me aparece así

![TECLADO DVORAK ESPAÑOL](https://user-images.githubusercontent.com/8141067/73690761-b392c300-4696-11ea-9a52-2987f603b6a0.png)

El teclado que estoy usando es un logitech u413 carbon

**Comment by janoamaral** [comment]
Correcto, ese modelo de teclado no tiene la **VK_OEM_102** (10 teclas en la línea). La alternativa que te propongo es utilizar la tecla **Ç** (c con cedilla) para los caracteres < y >.

![DvorakSP2](https://user-images.githubusercontent.com/10008708/73696032-1a75a380-46ba-11ea-9c62-8f1612ba60f3.jpg)
