### ISSUE TITLE
Necesita actualizacion para con os X

### ISSUE THREAD

**Issue by sir-farfan** [logico-dev/Spanish-Dvorak-Layout#3]
OS X 10.15.6 - Catalina

` % ls -l ~/Library/spanish_dvorak.keylayout
-rw-r--r--  1 yo  yo  18801 Aug 25 09:22 /Users/yo/Library/spanish_dvorak.keylayout`

Puse el archivo en Library, pero la distribucion no me aparece en las opciones de teclado.

Intente abrir los archivos dentro de OS X con Ukelele 3.4.2 pero dice que "no es un archivo XML valido"

**Comment by janoamaral** [comment]
Hola, no tengo más acceso a MacOS, por lo que momentáneamente no puedo ayudarlo. Dejo abierto y taggeo el issue. Si logra solucionarlo por favor haga un PR.

**Comment by NickG13** [comment]
Hola, he encontrado una solución a este problema https://adrianperales.com/2019/10/como-configurar-el-teclado-dvorak-espanol-en-macos/
