### ISSUE TITLE
No encuentra el fichero dvorakes_amd64.msi

### ISSUE THREAD

**Issue by sramirez94** [logico-dev/Spanish-Dvorak-Layout#4]
Muestra el siguiente mensaje cuando se ejecuta el instalador en Windows 11
---------------------------
Windows Installer Installation Wrapper
---------------------------
Setup was unable to find the msi package or patch 'C:\Users\Freeway\OneDrive\Documentos\dvorak en español\Spanish-Dvorak-Layout-master\Spanish-Dvorak-Layout-master\Windows\DvorakES\dvorakes_amd64.msi'.
---------------------------
Aceptar   
---------------------------

**Comment by janoamaral** [comment]
Intentá descomprimir el archivo en otra carpeta, Descargas por ejemplo.
